spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_RDS}:${DB_PORT_RDS}/${DB_NAME_RDS}
    username: ${DB_USER_RDS}
    password: ${DB_PASSWORD_RDS}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: '0'

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID_PROD}
            client-secret: ${GITHUB_CLIENT_SECRET_PROD}
